In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('drinks.txt')

In [3]:
df

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
...,...,...,...,...,...
188,Venezuela,333,100,3,7.7
189,Vietnam,111,2,1,2.0
190,Yemen,6,0,0,0.1
191,Zambia,32,19,4,2.5
192,Zimbabwe,64,18,4,4.7

#### Média e Desvio Padrão do consumo de cerveja, licor, vinho e total de álcool

In [11]:
media_consumo_cerveja = df['beer_servings'].mean()
dp_consumo_cerveja = df['beer_servings'].std()
print('Média consumo de litros de cerveja:',media_consumo_cerveja)
print('Desvio Padrão consumo de litros de cerveja:',dp_consumo_cerveja)

Média consumo de litros de cerveja: 106.16062176165804
Desvio Padrão consumo de litros de cerveja: 101.1431025393134

In [14]:
media_consumo_licor = df['spirit_servings'].mean()
dp_consumo_licor = df['spirit_servings'].std()
print('Média consumo de litros de licor:',media_consumo_licor)
print('Desvio Padrão consumo de litros de licor:',dp_consumo_licor)

Média consumo de litros de licor: 80.99481865284974
Desvio Padrão consumo de litros de licor: 88.2843121096862

In [15]:
media_consumo_vinho = df['wine_servings'].mean()
dp_consumo_vinho = df['wine_servings'].std()
print('Média consumo de litros de vinho:',media_consumo_vinho)
print('Desvio Padrão consumo de litros de vinho:',dp_consumo_vinho)

Média consumo de litros de vinho: 49.45077720207254
Desvio Padrão consumo de litros de vinho: 79.6975984576301

In [16]:
media_consumo_alcool = df['total_litres_of_pure_alcohol'].mean()
dp_consumo_alcool = df['total_litres_of_pure_alcohol'].std()
print('Média consumo de litros de alcool:',media_consumo_alcool)
print('Desvio Padrão consumo de litros de alcool:',dp_consumo_alcool)

Média consumo de litros de alcool: 4.717098445595855
Desvio Padrão consumo de litros de alcool: 3.7732981643560835

##### Outra maneira

In [22]:
md_cons_cerv = df.describe()['beer_servings']['mean']
dp_cons_cerv = df.describe()['beer_servings']['std']
print('Média de consumo de cerveja:', md_cons_cerv)
print('Desvio Padrão de consumo de cerveja:', dp_cons_cerv)

Média de consumo de cerveja: 106.16062176165804
Desvio Padrão de consumo de cerveja: 101.1431025393134

#### Qual o consumo de licor na França?

In [32]:
cons_licor_franca =  df[df['country'] == 'France']['spirit_servings'].values[0]
print('O consumo de licor na França é:', cons_licor_franca)

O consumo de licor na França é: 151

#### Quais os 5 países nos quais se consome mais vinho

In [44]:
top5_paises_vinho =  df.sort_values(by='wine_servings', ascending=False).head(5)['country'].values
print('Os 5 países que mais se consome vinho são: ', str(', ').join(top5_paises_vinho))

Os 5 países que mais se consome vinho são:  France, Portugal, Andorra, Switzerland, Denmark

#### Quais os países nos quais o consumo de cerveja está acima da média?

In [52]:
media_cerveja = df['beer_servings'].mean()
paises_media_cerveja = df[df['beer_servings'] > media_cerveja]['country'].values
paises_media_cerveja = str(', ').join(paises_media_cerveja)
print('Os países em que o consumo de cerveja está acima da média são:', paises_media_cerveja)

Os países em que o consumo de cerveja está acima da média são: Andorra, Angola, Argentina, Australia, Austria, Bahamas, Barbados, Belarus, Belgium, Belize, Bolivia, Botswana, Brazil, Bulgaria, Cabo Verde, Cameroon, Canada, Chile, Colombia, Costa Rica, Croatia, Cyprus, Czech Republic, Denmark, Dominican Republic, Ecuador, Estonia, Finland, France, Gabon, Germany, Greece, Grenada, Hungary, Iceland, Ireland, Kazakhstan, Latvia, Lithuania, Luxembourg, Malta, Mexico, Namibia, Netherlands, New Zealand, Niue, Norway, Palau, Panama, Paraguay, Peru, Poland, Portugal, South Korea, Moldova, Romania, Russian Federation, St. Kitts & Nevis, St. Lucia, St. Vincent & the Grenadines, Serbia, Seychelles, Slovakia, Slovenia, South Africa, Spain, Suriname, Sweden, Switzerland, Trinidad & Tobago, Ukraine, United Kingdom, USA, Uruguay, Venezuela, Vietnam

#### Países com consumo de álcool maior que o Brasil, ordem crescente

In [65]:
consumo_alcool_brasil = df[df['country'] == 'Brazil']['total_litres_of_pure_alcohol'].values[0]
consumo_alcool_brasil

np.float64(7.2)

In [70]:
mais_que_brasil = df[df['total_litres_of_pure_alcohol'] > consumo_alcool_brasil]
mais_que_brasil = mais_que_brasil.sort_values(by='total_litres_of_pure_alcohol')
mais_que_brasil

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
132,Paraguay,213,117,74,7.3
35,Chile,130,124,172,7.6
188,Venezuela,333,100,3,7.7
143,St. Kitts & Nevis,194,205,32,7.7
44,Cyprus,192,154,113,8.2
159,South Africa,225,76,81,8.2
32,Canada,240,122,100,8.2
67,Greece,133,112,218,8.3
179,Uganda,45,9,0,8.3
6,Argentina,193,25,221,8.3
184,USA,249,158,84,8.7
180,Ukraine,206,237,45,8.9
62,Gabon,347,98,59,8.9
124,Nigeria,42,5,2,9.1
121,New Zealand,203,79,175,9.3
120,Netherlands,251,88,190,9.4
57,Estonia,224,194,59,9.5
151,Serbia,283,131,127,9.6
9,Austria,279,75,191,9.7
138,South Korea,140,16,9,9.8
160,Spain,284,157,112,10.0
60,Finland,263,133,97,10.0
144,St. Lucia,171,315,71,10.1
166,Switzerland,185,100,280,10.2
42,Croatia,230,87,254,10.2
25,Bulgaria,231,252,94,10.3
48,Denmark,224,81,278,10.4
8,Australia,261,72,212,10.4
140,Romania,297,122,167,10.4
182,United Kingdom,219,126,195,10.4
16,Belgium,295,84,212,10.5
93,Latvia,281,216,62,10.5
156,Slovenia,270,51,276,10.6
135,Poland,343,215,56,10.9
136,Portugal,194,67,339,11.0
65,Germany,346,117,175,11.3
75,Hungary,234,215,185,11.3
155,Slovakia,196,293,116,11.4
99,Luxembourg,236,133,271,11.4
81,Ireland,313,118,165,11.4
141,Russian Federation,247,326,73,11.5
61,France,127,151,370,11.8
45,Czech Republic,361,170,134,11.8
68,Grenada,199,438,28,11.9
3,Andorra,245,138,312,12.4
98,Lithuania,343,244,56,12.9
15,Belarus,142,373,42,14.4